POST https://bidprosapi.herokuapp.com/api/events HTTP/1.1
Content-Type: application/json

{
    "name": "A Night to Remember",
    "organization": "Dell Children's Medical",
    "email": "dell@fakegmail.com"
}
