POST http://localhost:3000/api/events HTTP/1.1
Content-Type: application/json

 {
     "name": "Jayden's Home for Homeless People",
     "organization": "Jayden's Living Room",
     "email": "jaydensaves@gmail.com"
}